### ISSUE TITLE
QUESTION: What happens with the data in the database

### ISSUE THREAD

**Issue by Lichtjaeger** [losandes/socket.io-mongodb#2]
There is no TTL index on the collection. How do you clean up these masses of documents.

Is this module a big memory leak?

**Comment by losandes** [comment]
This module depends on [mubsub](https://github.com/scttnlsn/mubsub), which uses [capped collections](https://docs.mongodb.com/manual/core/capped-collections/), so cleanup happens by virtue of use.

**Comment by subversivo58** [comment]
I know this question is closed, but how to set the collectiono will be created with attributes capped true e size ?

**Comment by losandes** [comment]
Hi @subversivo58. Check out the answer to https://github.com/losandes/socket.io-mongodb/issues/3

**Comment by subversivo58** [comment]
thank you, resolved issue
